export const LOAD_HOLIDAYS_SUCCESS = 'LOAD_HOLIDAYS_SUCCESS';

export const CHANGE_DATE_HOLIDAY = 'CHANGE_DATE_HOLIDAY';
export const CHANGE_RULE_TYPE = 'CHANGE_RULE_TYPE';

export const INCREMENT_YEAR = 'INCREMENT_YEAR';
export const DECREMENT_YEAR = 'DECREMENT_YEAR';

export const CHANGE_MONTH='CHANGE_MONTH';
export const CHANGE_DAY_OF_MONTH='CHANGE_DAY_OF_MONTH';
export const CHANGE_DAY_OF_WEEK='CHANGE_DAY_OF_WEEK';
export const CHANGE_BEGINS='CHANGE_BEGINS';
export const CHANGE_ENDS='CHANGE_ENDS';
export const CLEAR_BEGINS='CLEAR_BEGINS';
export const CLEAR_ENDS='CLEAR_ENDS';


export const CHANGE_MESSAGE='CHANGE_MESSAGE';


