export const LOAD_HOLIDAYS_SUCCESS = 'LOAD_HOLIDAYS_SUCCESS';

export const CHANGE_DATE_HOLIDAY = 'CHANGE_DATE_HOLIDAY';

export const INCREMENT_YEAR = 'INCREMENT_YEAR';
export const DECREMENT_YEAR = 'DECREMENT_YEAR';