export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS';
export const LOAD_HOLIDAYS_SUCCESS = 'LOAD_HOLIDAYS_SUCCESS';

export const INCREMENT_YEAR = 'INCREMENT_YEAR';
export const DECREMENT_YEAR = 'DECREMENT_YEAR';

export const CREATE_NEW_HOLIDAY= 'CREATE_NEW_HOLIDAY';

export const HOLIDAY_RULE_DATE= 'HOLIDAY_RULE_DATE';
export const HOLIDAY_RULE_DAY_OF_WEEK= 'HOLIDAY_RULE_DAY_OF_WEEK';
export const HOLIDAY_RULE_DAY_OF_MONTH= 'HOLIDAY_RULE_DAY_OF_MONTH';
export const HOLIDAY_RULE_WITH_INTERVAL= 'HOLIDAY_RULE_WITH_INTERVAL';


